name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_run:
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ github.event_name }}
      output2: ${{ github.ref }}
    steps:
      - name: List all files
      - uses: actions/checkout@v4.1.7
      - run: ls
